name: Backup Diário do Firestore

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  firestore-backup:
    runs-on: ubuntu-latest

    # ADICIONE ESTE BLOCO DE PERMISSÕES
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # =================================================================
      # ETAPA DE AUTENTICAÇÃO OFICIAL (A GRANDE MUDANÇA)
      # =================================================================
      - name: Autenticar com Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Firebase Admin SDK
        run: npm install firebase-admin

      # Agora o script de backup não precisa mais da variável de ambiente
      - name: Gerar arquivo de backup
        run: node backup.js backup-$(date +%u).json

      - name: Commit do arquivo de backup
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Backup automático do Firestore"
          file_pattern: "backup-*.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
